### ISSUE TITLE
The description of Use As Image in README.md is incorrect.

### ISSUE THREAD

**Issue by JihunDev** [codersrank-org/work-experience-widget#4]
The description of Use As Image in README.md is incorrect.

`
<img
  src="https://cr-ss-service.azurewebsites.net/api/ScreenShot?widget=education&username=YOUR_USERNAME&max-items=2&logos=true&style=--item-bg-color:%23f00;--item-border-radius:10px"
/>
`

For example of Use As Image is a way to express education.

The widget should change to work-experience.

**Comment by peti2001** [comment]
Fixed, thanks!
